### ISSUE TITLE
Developer instructions how to run the server

### ISSUE THREAD

**Issue by ubruhin** [opacopac/navplan#21]
Is there any (rudimentary) documentation available how to run navplan on an own server, for example to test features during development? Is this even possible with reasonable effort? What services (e.g. database) are needed?

After commenting out the redirection to navplan.ch in `index.php` (because `$_SERVER['HTTP_HOST'] != $host`), I was able to run the site in a docker container with this command:

```bash
docker run -it --rm -u 1000:1000 -v `pwd`:/var/www/html -p 8080:80 php:apache
```

However, (of course) there is not much functionality (no map, no user management, ...) :grin:

**Comment by opacopac** [comment]
hi mr. bruhin

while it might technically be possible to run the full navplan website for personal experiments on an own server, it's actually discouraged to do so, as e.g. own api keys would be needed for accessing external data sources and the installation would be quite complex involving db & several file sources that have to be set up seperately additionally to the source code posted on github. i cannot give any support here, sorry.

greetings,
armand

**Comment by ubruhin** [comment]
Hi,

OK I see. It's a pity, but I understand your explanation.

Thanks anyway ;)
