### ISSUE TITLE
Wrong frequency for LSZR GND

### ISSUE THREAD

**Issue by Luz** [opacopac/navplan#25]
When adding LSZR to the destinations, the communication frequencies are listed (among other information, e.g. runways and airport elevation). The GND frequency seems to be wrong:

Printed GND frequency: 121.800
Expected GND frequency: 121.805

At least according to the current VFR chart.

**Comment by opacopac** [comment]
hi luz!

thanks for the notification! i've updated the frequency to 121.805.

greets,
armand
