### ISSUE TITLE
EET does not take Ground Speed into Account

### ISSUE THREAD

**Issue by thesnert** [opacopac/navplan#28]
First and foremost, thanks for a really awesome tool!

In the Route & Fuel tab, the EET for each waypoint is correctly calculated for a 100kt GS. The total EET takes the GS field into account, however, the individual items are not being updated.

**Comment by opacopac** [comment]
thanks a lot for the info, it was indeed a bug, the individual waypoints were not updated when changing the ground speed. it's now fixed!

**Comment by thesnert** [comment]
Hey, thanks so much for fixing this so fast! :)
